// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzItV-N7LJYRjQrSfIR0F59ckt3uNGTkc',
    appId: '1:334611174178:android:eed942b50db82ba55a4b7b',
    messagingSenderId: '334611174178',
    projectId: 'xara-8255c',
    storageBucket: 'xara-8255c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6JGtFvD651i2VqG29aFaMXheJZDSGT1U',
    appId: '1:334611174178:ios:1c8788c5031405eb5a4b7b',
    messagingSenderId: '334611174178',
    projectId: 'xara-8255c',
    storageBucket: 'xara-8255c.appspot.com',
    androidClientId: '334611174178-dsvag9h3l5aqgv4115fmfe4f4s8ur3eg.apps.googleusercontent.com',
    iosClientId: '334611174178-3b049po3vn8vjmvkhefqsgbrnf1jgsij.apps.googleusercontent.com',
    iosBundleId: 'com.example.botchefV2Admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6JGtFvD651i2VqG29aFaMXheJZDSGT1U',
    appId: '1:334611174178:ios:1c8788c5031405eb5a4b7b',
    messagingSenderId: '334611174178',
    projectId: 'xara-8255c',
    storageBucket: 'xara-8255c.appspot.com',
    androidClientId: '334611174178-dsvag9h3l5aqgv4115fmfe4f4s8ur3eg.apps.googleusercontent.com',
    iosClientId: '334611174178-3b049po3vn8vjmvkhefqsgbrnf1jgsij.apps.googleusercontent.com',
    iosBundleId: 'com.example.botchefV2Admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDk4VyH5G_F6UwVtPNWTGEJgQtEbPMNGA',
    appId: '1:334611174178:web:42542d136c715f365a4b7b',
    messagingSenderId: '334611174178',
    projectId: 'xara-8255c',
    authDomain: 'xara-8255c.firebaseapp.com',
    storageBucket: 'xara-8255c.appspot.com',
    measurementId: 'G-0T5FD6KWVM',
  );
}
